import {
  Apply,
  Call,
  Call2,
  Call3,
  Call4,
  Call5,
  Eval,
  Fn,
  Pipe,
  PipeRight,
  Compose,
  ComposeLeft,
  Constant,
  Identity,
  PartialApply,
  _,
  arg,
  arg0,
  arg1,
  arg2,
  arg3,
  args,
} from "./internals/core/Core";
import { Parser } from "./internals/parser/Parser";
import { Functions } from "./internals/functions/Functions";
import { Numbers } from "./internals/numbers/Numbers";
import { Objects } from "./internals/objects/Objects";
import { Strings } from "./internals/strings/Strings";
import { Tuples } from "./internals/tuples/Tuples";
import { Unions } from "./internals/unions/Unions";
import { Booleans } from "./internals/booleans/Booleans";
import { Match } from "./internals/match/Match";

export {
  _,
  arg,
  arg0,
  arg1,
  arg2,
  arg3,
  args,
  Fn,
  Pipe,
  PipeRight,
  Call,
  Call2,
  Call3,
  Call4,
  Call5,
  Compose,
  ComposeLeft,
  Constant,
  Identity,
  PartialApply,
  Apply,
  Eval,
  Match,
  Booleans,
  Objects,
  Unions,
  Strings,
  Numbers,
  Tuples,
  Functions,
  Parser,
  Booleans as B,
  Objects as O,
  Unions as U,
  Strings as S,
  Numbers as N,
  Tuples as T,
  Functions as F,
  Parser as P,
};
